name: Test Build (Manual)

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_desktop.txt
        Write-Host "✓ Dependencies installed"
    
    - name: Test Python scripts
      run: |
        Write-Host "Testing Python imports..."
        python -c "import cv2; print('✓ OpenCV imported')"
        python -c "import numpy; print('✓ NumPy imported')"
        python -c "import tkinter; print('✓ Tkinter imported')"
        python -c "from PIL import Image; print('✓ PIL imported')"
        try {
          python -c "import pyzbar; print('✓ pyzbar imported')"
        } catch {
          Write-Host "⚠ pyzbar not available (using OpenCV fallback)"
        }
    
    - name: Build EXE
      run: |
        Write-Host "Building EXE..."
        python pyinstaller_spec.py
    
    - name: Test EXE
      run: |
        if (Test-Path ".\dist\BarcodeReader.exe") {
          Write-Host "✓ EXE created successfully"
          $fileSize = (Get-Item ".\dist\BarcodeReader.exe").Length / 1MB
          Write-Host "✓ File size: $([math]::Round($fileSize, 1)) MB"
        } else {
          Write-Host "✗ EXE not found"
          exit 1
        }
    
    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: BarcodeReader-Test
        path: dist/BarcodeReader.exe
        retention-days: 7
